[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "account-abstraction/=lib/account-abstraction/contracts/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
# in order to use the system contracts of zkSync, we need to set this to true
is-system = true
via-ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
